# The parameters "input", "output", "reference" and "primer" are the absolute paths. Do not include the "/" at the end of the paths.
input          : "/path/to/fastqs"
output    : "/path/to/output"
reference      : "/path/to/reference"
primer    : "/path/to/primers"
# specify if input amplicons were fragmented. If yes, the parameter setting is "frag". If no, the parameter setting is "no_frag". (default: frag)
frag : "frag"
# comma separated list of SOTCs to screen, default as "S:L452R,S:E484K"
sotc : "S:L452R,S:E484K"


